# The name must be a single word
name : cm8f
# Define the rules for this style
file_list :
  - ./**/hdl/*.vhd 

rule :
  global:
    compact_alignment : false
    blank_line_ends_group: true
    comment_line_ends_group : false
    separate_generic_port_alignment : false
    if_control_statements_end_group : false
    case_control_statements_end_group : false

  instantiation_034:
     method: 'entity'
  # Set Uppercase rules
  architecture_004:
    case : upper
  architecture_009:
    case : upper
  architecture_019:
    case : upper
  architecture_020:
    case : upper
  architecture_021:
    case : upper
  architecture_028:
    case : upper

  attribute_declaration_500:
    case : upper
  attribute_declaration_501:
    case : lower
  attribute_declaration_502:
    case : upper
  attribute_specification_501:
    case : upper
  attribute_specification_502:
    case : lower
  attribute_specification_503:
    case : upper

  case_014:
    case : upper
  case_015:
    case : upper
  case_016:
    case : upper
  case_017:
    case : upper
  case_018:
    case : upper

  constant_002:
    case : upper
  constant_004:
    case : lower
  constant_011:
    disable : true
    case : upper

  context_004:
    case : upper
  context_012:
    case : lower
  context_013:
    case : upper 
  context_014:
    case : upper 

  context_ref_003:
    case : upper 

  entity_006 :
    case : upper
  entity_010 :
    case : upper
  entity_014 :
    case : upper

  function_004:
    case : upper 
  function_005:
    case : upper 
  function_013:
    case : upper 
  function_014:
    case : upper 


  generate_009 :
    case : upper
  generate_010 :
    case : upper

  generic_009 :
    case : upper
  generic_017:
    case : upper

  generic_map_001:
    case : upper
  generic_map_002:
    case : lower

  if_025:
    case : upper 
  if_026:
    case : upper 
  if_027:
    case : upper
  if_028:
    case : upper
  if_029:
    case : upper 
  if_034:
    case : upper

  instantiation_027:
    case : upper
  instantiation_031:
    case : upper

  library_004:
    case : upper
  library_005:
    case : upper

  component_004:
    case : upper
  component_006:
    case : upper 
  component_010:
    case : upper
  component_014 : 
    case : upper

  package_004:
    case : upper
  package_006:
    case : upper
  package_013:
    case : upper
  package_018:
    case : upper 

  package_body_500:
    case : upper 
  package_body_501:
    case : upper
  package_body_503:
    case : upper
  package_body_504:
    case : upper
  package_body_505:
    case : upper
  package_body_506:
    case : upper

  port_010 :
    case : lower
  port_017:
    case : upper
  port_018:
    case : upper
  port_019:
    case : upper



  port_map_001:
    case : upper
  port_map_002:
    case : lower

  procedure_008:
    case : upper
  procedure_009:
    case : upper 

  process_004:
    case : upper 
  process_005:
    case : upper 
  process_008:
    case : upper 
  process_009:
    case : upper 
  process_012:
    disable : true
  process_013:
    case : upper 

  report_statement_500:
    case : upper
  report_statement_501:
    case : upper 

  range_001:
    case : upper
  range_002:
    case : upper

  signal_002:
    case : upper
  signal_010:
    case : upper 
    disable : false
  signal_011:
    disable : true
  signal_007:
    disable : true
  
  type_002:
    case : upper 
  type_013:
    case : upper 

  variable_002:
    case : upper 
  variable_010:
    disable : true

  # set prefix/suffix
  constant_015:
    disable : false
    prefixes : ['c_']
  generate_017:
    disable : false 
    prefixes : ['gen_']
  generic_020:
    disable : false 
    prefixes : ['g_']
  package_016:
    disable : false 
    suffixes : ['_pkg']
  package_body_600:
    disable : false 
    suffixes : ['_pkg']
  port_011:
    disable : false
    prefixes : ['i_', 'o_', 'io_']
  process_036:
    disable : false
    prefixes : ['proc_']
  signal_008:
    disable : false
    prefixes : ['s_', 'r_', 'sm_']
  subtype_004:
    disable : false
    prefixes : ['t_']
  type_015:
    disable : false
    prefixes : ['t_']
  variable_012:
    disable : false
    prefixes : ['v_', 'sv_']

  # Set alignment rules
  architecture_026 :
    compact_alignment : false
    blank_line_ends_group : false
    comment_line_ends_group : false
  architecture_027 :
    compact_alignment : false
    blank_line_ends_group : false
    comment_line_ends_group : false
  component_017 :
    compact_alignment : false
    blank_line_ends_group : false
    comment_line_ends_group : false
  concurrent_008 :
    compact_alignment : false
    blank_line_ends_group : true
    comment_line_ends_group : true
  entity_017 :
    compact_alignment : false
    blank_line_ends_group : false
    comment_line_ends_group : false
  entity_018 :
    compact_alignment : false
    blank_line_ends_group : false
    comment_line_ends_group : false
  entity_020 :
    compact_alignment : false
    blank_line_ends_group : false
    comment_line_ends_group : false
    seperate_generic_port_alignment : true
  process_034 :
    compact_alignment : false
    blank_line_ends_group : false
    comment_line_ends_group : false
  process_035 :
    compact_alignment : false
    blank_line_ends_group : false
    comment_line_ends_group : false
    include_lines_without_comments : false
  sequential_005 :
    compact_alignment : true
    blank_line_ends_group : true
    comment_line_ends_group : true
