name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: docker://ghdl/vunit:gcc
        with:
          args: python3 ./run.py -p 6 --cover 1
