name: CI

on: [push]

jobs:
  vunit-ghdl-sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: docker://ghdl/vunit:gcc
        with:
          args: python3 ./run.py -p 6 --cover 1

      - uses: codecov/codecov-action@v1.3.1
        with:
          files: ./coverage.txt # optional
          flags: unittests # optional
          name: codecov # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
