name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: VUnit/vunit_action@master
        with:
          cmd: ./run.py -p6 -x output.xml --xunit-xml-format jenkins --exit-0 --no-color --cover 1 
