name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghdl/vunit:gcc
    steps:
      - uses: actions/checkout@v1
      - run: python3 ./run.py -p6 -x output.xml --xunit-xml-format jenkins --exit-0 --no-color --cover 1 
      - name: run simulation
